theme: jekyll-theme-slate
title: This is the personal homepage of Quan, boba lover and avid book reader.
description: What you will find here are favorite photos from my daily life.
plugins:
  - jemoji
url: "https://shironekoii133.github.io/"
markdown: kramdown
